name: ecommerce workflow
on:
 push:
   branches: [main]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: install dependencies
        run: npm install
      - name: Run tests
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    #if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy the placeholder
        run: echo "working successfully"
