name: ecommerce workflow
on:
 push:
   branches: master
 jobs:

   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: action/checkout@v4
       - name: setup node.js
         uses: action/setup-nodev4
         with:
           node-version: '16'

       - name: install dependencies
         run: npm install
       - name: Run tests
         run: npm run build
